#  Stage 1: Build 
FROM golang:1.26-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux \
    go build -o /bin/worker ./cmd/worker && \
    chmod +x /bin/worker
#  Stage 2: Run 
FROM alpine:latest

COPY --from=builder /bin/worker /worker
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ENTRYPOINT ["/worker"]
