FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux \
    go build -o /bin/api ./cmd/server && \
    chmod +x /bin/api

FROM alpine:latest

# alpine already has SSL certs — no need to copy them
WORKDIR /app
COPY --from=builder /bin/api /api

EXPOSE 8080
ENTRYPOINT ["/api"]