#  Stage 1: Build 
FROM golang:1.22-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
# Downloads and caches Go dependencies separately for faster builds.
# /go/pkg/mod
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/api ./cmd/server

# Stage 2: Run 
# Use a minimal image — no shell, no package manager, just the binary
FROM scratch

COPY --from=builder /bin/api /api
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

EXPOSE 8080
ENTRYPOINT ["/api"]
